language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  
os:
  - linux
  - osx

dist: xenial

services:
  - xvfb

script: xvfb-run make test

install:
  - pip install .

script:
  - python -m unittest discover -v test
