language: python

python:
  - 3.6
  - 3.7
  - 3.8

obs:
  include:
    - os: linux
    - os: osx
      language: minimal
    - os: windows
      language: minimal
      before_install:
      - choco install python3
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

dist: xenial

services:
  - xvfb

script: xvfb-run make test

install:
  - pip install .

script:
  - python -m unittest discover -v test
