env:
  global:
    - secure: E4fg9ECX3zbiNFpJhC6XzHkUgic1o5no50+AGGat4/ePzr9Zzgesw5id8K2N3VoMxYaOkjPvwfVHYkO+6BIs5zDXa2wDPegkdpYWopovfMXziP7ibMwlHlYEICuJqsKqMuAthhnAnGf0kMoB2oOcZbyp8NrXiDsZnMXGMZkmrzJWfgvObJwRn6N4kw/O9Ge/hYHBOfZ2FQGOm04NkGgM7kfOH5RailI37lwgRLcyZAYPvJh6kZQ5FB4881AsI/2pU/YeNEZiJmhwRgNvlovl9bwZEJ2xUSV/raOcgME8nCVKKuyuNMKwSiYOSTmoB7zE3r8ItuZugn0d1PiYHS7qnyx5PEzvp1tiz4HQ5NW+m0XHIKrelIWSurOJMZXW+ykiFlM6GsntnCkhGp81s8/UFaJCxmftNWVtUwB2F7b/h1eYTaeTOeeuINTLjCkXMuDhQvGscv6RyUtRWeWRxVSSlMhIJTt2fgjSLWFrQPCCAgH0GRmDmurtBAZudvIruUwQH/pfBe/9p9wn8EDHSE2iB8/kEMbaO0kDei4V6Rh0vR5S58pQlqKU9UkFnNiiZ2YvqCyIfP3qIqQ7F8UWJqY6jXVzjEvY7sYnFentLs9pbkg37pUCfhw0t4ZMsOGEaX1yW92iwbV8iD3c5uMIoInZ9u3X220jD/tI/GULi2iMf3A=
    - secure: WRl34iTBVKJ7W1Aiz7gQdHYMZvBNxnhetjyA8HFKW3zslv6TEEO7hjoohpzP6DkhK7sTZipmz5rrtxED8mxA4r+JX2FOOjm3A7VzzXAXC5iOcctsanDr+w9gGupHOYJo0z5SMuDh1uIt9JAoniAAJ4cjQKdhJ9NRKqv5FPyJk0D6uCuYcCL4cXrleSzgkD9Ssrqe2w82P/2VHqTa8YV7KK8VIyS9u0lVylC86ztDpw82J+z+kDMY69VwdEIMNW393oD58ahLTo7ZQrowjg/zpNUYu5wB8BtYUIMdyMFZT8286OlW2TXHmuZ+UTMvWMO/amg1bEMCbRkUxJc5ohfl4bpa2cGbepmF7xMgg5o1pfuvOpFr+CdFtRbaQeCbyLjdJ7mxGkg/OUoEaxIo3hu0ybzv2sFgk8FfQ0lIylQ4XYQaaP0/2xZ2ibX9im4hyF2WknWMUisLyDL5ZnNYzmae4H2Q+i0nNXO4ZRSTkY99QQr/RoKb4OBSPBhKsq8ll4h1vIIPkH7ZF0Neanqn1ZVSzdHHeloANy1DdRR+XvUtsJlRgflWDh7nfG6mNbiLMqQcVKO47AAELHBdfM0YXj0lHglPgy2BbCL0xL16In5SQelr6qsFEqyTEcyjTqLOWuoHBBTFmsQP1BPkIS5iR38vi9FU7kMRdMEZgoPBgUaeVpI=
    - secure: Mok2UK5uwfZ2iJDJ3FemTdtDhhGPal+W+MLBclYVuxELKibzkW95cPEzagaMTGcWaM+VWmCP/MwTHsTPeZC0dLRXs4p1+nkgk5/iZUykgn5gO9Qaje0rvoQXdnvVIwsr/LsjC8m0J6ledI+fJHg3yvJtcmz/tYRJmzHFmK56YKIfNJgv5X7Y5IyahkM23b/Cas4AcmLsF5Rw19x40zEwbPv6SEMzC14VxBMPaHDe69+RmAJGtfHM96HfI/MNkvvjxhfoW5wyuletC+jy4yQXnfUiPHok/UxeuYvC1e0JRo4QvI7eH+5J7yX4AdHeje9maZ72XZcbzo/UbFUw980bqEXOQ1PzS7ZTxw7i/NsgpAB24KKqIrRiPSfe9v7qQFlHFHndpYDhqalcltWg+/vRnbc/9PfHiUc8ttOZLcjEhdvvHlvlgABn2LkEB0mdN/z9DoCwshwI/Gh/h4C05c0kJN64jjJXRalEOalX/v9LHA6RUIW0sXKkR2h1EZhHQy4XPkykbkia0tuAQExTLhvLY6ZqCxxL5kXS5zzH1wJOSKywDGiEx/XmEROeuevckqZjMAau90P8bzxsnOOb6HautNI8wnHffPQoj1rs/UuXrFHBg87H6uowM4UZo32JcZ2rtZmGZwMVLUtjC42tTXVAaRm0TQrIuq6Qrlx7Y5ZC6/s=
    - secure: pSo6FjrRg34JGaAq1P2gNJSxbjq73EFIszO0V7voOHquFClzjcHVJHCnDG57hJdsNuKTYgwnUW2ux7wlPmLk121XVH1VBHpf2qbhorM1CZdvMvMXzFDH3TPDbxtLEQdTZTe2/edTcL3QNW4D4UwOk/pVSsGlsFgapCJKRF93/CvHTyJ/DHtwaJuchyjdm1mIE3owUY/fdZso3YI72haA0EpDml5fGiwI5AejEghDWVLQ0JuEmG7Y2yoqciEOZ6b/881HxQoSkrxF/AT5VHoqgB4Ufle5gV2iSNlXkonuLFMoBCz7z8jjD4v3/FdfnB8WJNVKgxQYkvqKyL6y8MboihJyNhWJEz1ovw/KJlLCOxBY4d8InZOGg5rjEaEgmbDkwBCsWvceeBvctKMh6HRc/Wi48rIu4Zk525gvR3FLAS/Ogzb+YbT3iOYHTZiKN8IvhJndF91gdwn/ywmVy1jAR2eQwjs6f8TQlAMUVqKUs9ao2/+fJtttxn45qzMzlQ+rmZ+ji7u5AGoeqFplrrLNjqiITi4dwxoM6/MEGu+P+qaNxwWaxjioEntoM6wOVE7gFmpzhgTZStXGW1cGdBOcIbcQ/lEifZD9e+IIEfOyjjSDGeJQcqGYlAwPy3kFYTnqlOXjdD1SpVzcC4SUNefq/SOCLfbrC1xLHq4l1O3ZNgY=

language: python

services:
  - xvfb

jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8

    - name: "Python 3.7.5 on macOS 9.4"
      os: osx
      osx_image: xcode9.4
      language: shell
    - name: "Python 3.7.5 on macOS 10.2"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.7.5 on macOS 10.3"
      os: osx
      osx_image: xcode10.3
      language: shell

    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

before_install:
  - python3 --version || python --version
  - pip3 install --upgrade pip

install:
  - pip3 install .

script:
  - python3 -m unittest discover -v test || python -m unittest discover -v test
