language: python

obs:
  include:
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py37
    - os: osx
      language: generic
      env: TOXENV=py38

dist: xenial

services:
  - xvfb

script: xvfb-run make test

install:
  - ./.travis/install.sh
  - pip install .

script:
  - python -m unittest discover -v test
